### ISSUE TITLE
Use ContributorRole instead of String in ContributorAttributes

### ISSUE THREAD

**Issue by chemicus** [ORCID/orcid-model#46]
#The intended comparison of the ContributorRole in https://github.com/ORCID/orcid-model/blob/c254ea569c8bd0c980a73d1d98c9514d12d6cffe/src/main/java/org/orcid/jaxb/model/v3/release/common/ContributorAttributes.java#L106 currently doesn't make any sense, since contributorRole is currently a String. https://github.com/ORCID/orcid-model/blob/c254ea569c8bd0c980a73d1d98c9514d12d6cffe/src/main/java/org/orcid/jaxb/model/v3/release/common/ContributorAttributes.java#L51 Most likely it is intended to use the ContributorRole type here instead?

I've already opened a pull request (#45) for this issue

**Comment by wjrsimpson** [comment]
@chemicus Thanks for the PR. I think that makes sense.

@amontenegro Can you check and work with Paula to get this into our QA and release cycle?

**Comment by amontenegro** [comment]
Thanks @chemicus! Thanks for the contribution, I will review your PR and merge it or comment on it in the next sprint.

You can track the progress of this here https://trello.com/c/aSn8tGLa

Thanks

**Comment by amontenegro** [comment]
Hey @chemicus.

Thanks a lot for your contribution, however, we will not merge you PR because it doesn't handle the contributors roles as we expected them to work, let me explain why:

Since April 2021 ORCID supports the CRediT taxonimy https://credit.niso.org/ and it is the set of values allowed in any new publication when using the API 3.0 or the UI, some links for more context:

- https://trello.com/c/KY5swGXn/242-add-contributor-roles-based-on-credit-taxonomy
- https://trello.com/c/KvXGi49s/52-add-contributor-roles-to-api-based-on-credit-contributor-roles-taxonomy

When we were working on adopting the CRediT taxonomy, we recognized the possiblity of adopting other taxonomies in the future, so, if we set the possible values either in the [schema description](https://github.com/ORCID/orcid-model/blob/master/src/main/resources/common_3.0/common-3.0.xsd#L905)  or in the [java enum](https://github.com/ORCID/orcid-model/blob/master/src/main/java/org/orcid/jaxb/model/v3/release/common/ContributorAttributes.java#L51) we will make adopting new taxonomies harder, because we would have to modify the model, publish it and update it in the ORCID-Source project.

Other problem that we faced is with backwards compatibility for contributors previously added, so, we needed a way to be able to hold any available value in the contributor role wihtout causing an schema validation error.

This is why we decided to leave the contributor role value as a string field, so, we can support the previous values and we could support more values in the future without the need of publishing the orcid-model again.

So, now on, for the V3.0 of the ORCID API, the list of allowed values is defined by enums in the  [ORCID-Source project] (https://github.com/ORCID/ORCID-Source), so, for example, the allowed CRediT role values is defined [here](https://github.com/ORCID/ORCID-Source/blob/development/orcid-core/src/main/java/org/orcid/core/contributors/roles/credit/CreditRole.java#L5) and then, a converter will be used to validate the value before it is persisted: https://github.com/ORCID/ORCID-Source/blob/development/orcid-core/src/main/java/org/orcid/core/contributors/roles/ContributorRoleConverterImpl.java

For the previous API version V2.0 and V2.1, the allowed values were defined in the enum [ContributorRole.java] (https://github.com/ORCID/orcid-model/blob/master/src/main/java/org/orcid/jaxb/model/message/ContributorRole.java).

Again, thanks a lot for your contribution on this, hope this explanation helps you understand how we handle the contributor roles and why we leave it as a string field.

**Comment by chemicus** [comment]
Hi @amontenegro,

It's ok for me to leave the contributorRole type as it is, but then the above mentioned comparison https://github.com/ORCID/orcid-model/blob/c254ea569c8bd0c980a73d1d98c9514d12d6cffe/src/main/java/org/orcid/jaxb/model/v3/release/common/ContributorAttributes.java#L106 needs to be changed as suggested in the new PR #47 as the operator != does not check for equality of the String content but only for the equality of the String references.

**Comment by amontenegro** [comment]
@chemicus you are right!!!! I just approved and merged your PR, thanks a lot!

We will publish a new version of the orcid-model soon (April probably) that will include your changes along with some other improvements.

[https://mvnrepository.com/artifact/org.orcid/orcid-model](https://mvnrepository.com/artifact/org.orcid/orcid-model)

Thanks again!
